"""
Django settings for ecommerce_konrad project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os 
from pathlib import Path
# pyrefly: ignore [missing-import]
from decouple import config
from datetime import timedelta

# [PATRÓN DE DISEÑO: SINGLETON]
# Django maneja un único objeto de configuración (Settings) garantizando 
# que todos los módulos consulten la misma y única fuente de parámetros globales.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# ============================================================
# RNF SEGURIDAD #2: Toda comunicación asegurada con HTTPS
# ============================================================
# En producción (DEBUG=False), Django redirige todo tráfico HTTP → HTTPS
# y activa cabeceras de seguridad estándar.
if not DEBUG:
    # Redirige automáticamente cualquier petición HTTP a HTTPS
    SECURE_SSL_REDIRECT = True
    # Indica al navegador que solo use HTTPS durante 1 año
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Las cookies de sesión y CSRF solo se envían por HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Protección contra contenido mixto (HTTP dentro de HTTPS)
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    # En desarrollo local se permite HTTP para facilitar el trabajo
    SECURE_SSL_REDIRECT = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps del proyecto
    'vendors',
    'directors',
    'buyers',
    'products',
    'orders',
    'payments',
    'notifications',
    'audit',
    'bam',
    'external_mocks',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'ecommerce_konrad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ecommerce_konrad/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_konrad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        # RNF Seguridad #2: conexión cifrada con la BD en producción
        'OPTIONS': {
            'sslmode': config('DB_SSL_MODE', default='prefer'),
        },
    }
}


# Password validation — RNF Seguridad #3
# La contraseña debe tener mínimo 8 caracteres con al menos
# una mayúscula, una minúscula y un número.
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # RNF #3: Validador personalizado (mayúscula + minúscula + número + 8 chars)
        'NAME': 'ecommerce_konrad.validators.RNFPasswordValidator',
    },
    {
        # No puede ser similar al nombre de usuario o email
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Mínimo 8 caracteres (refuerza el RNF #3)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        # No puede ser una contraseña común (ej: "password123")
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CONFIGURACIÓN DE SEGURIDAD PARA LA API (DRF)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Por defecto, todas las respuestas requieren estar autenticado
    # (Esto lo podemos cambiar ruta por ruta después)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CONFIGURACIÓN DEL SERVIDOR DE CORREOS AUTOMATIZADOS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# RNF Seguridad #2: restringir orígenes CORS — en producción usar dominio real
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # Solo en desarrollo
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:3000'
    ).split(',')

# CONFIGURACIÓN DE LOGGING PARA CAPTURAR ERRORES EN LA BASE DE DATOS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'db_log': {
            'level': 'ERROR',
            'class': 'audit.handlers.DBLogHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Captura errores de Django (vistas, base de datos, etc)
        'django': {
            'handlers': ['db_log', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
        # Captura errores de nuestras propias apps
        'audit': {
            'handlers': ['db_log', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
