# Generated by Django 6.0.3 on 2026-03-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_detalleorden_options_alter_detalleorden_orden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito/Débito'), ('PSE', 'PSE'), ('EFECTIVO', 'Efectivo / Puntos físicos')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='orders.orden')),
            ],
            options={
                'verbose_name': 'Pago de Orden',
                'verbose_name_plural': 'Pagos de Órdenes',
            },
        ),
    ]
