# Generated by Django 6.0.3 on 2026-03-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_consignacionbancaria_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignacionbancaria',
            name='pago_orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignacion', to='payments.pagoorden'),
        ),
    ]
