# Generated by Django 6.0.3 on 2026-03-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_consignacionbancaria_pago_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='tipo',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20),
        ),
    ]
