# Generated by Django 6.0.3 on 2026-04-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_suscripcion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoorden',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
