# Generated by Django 6.0.3 on 2026-03-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
