# Generated by Django 6.0.3 on 2026-04-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_comprador_instagram_comprador_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nombre', models.CharField(help_text='Ej: Nu, Bancolombia, Nequi', max_length=100)),
                ('titular_nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito / Débito'), ('CUENTA', 'Cuenta Bancaria'), ('BILLETERA', 'Billetera Digital (Nequi/Daviplata)')], default='TARJETA', max_length=20)),
                ('numero_cuenta_tarjeta', models.CharField(help_text='Número de cuenta o tarjeta', max_length=20)),
                ('token_seguridad', models.CharField(blank=True, help_text='Simulación de Token/OTP', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='buyers.comprador')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
    ]
