# Generated by Django 6.0.3 on 2026-03-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogVisitaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(blank=True, help_text='Ej: instagram, twitter, directo', max_length=50, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='products.producto')),
            ],
            options={
                'verbose_name': 'Log de Visita a Producto',
                'verbose_name_plural': 'Logs de Visitas a Productos',
            },
        ),
    ]
