# Generated by Django 6.0.3 on 2026-03-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_afectada', models.CharField(help_text='Ej: Orden, Producto, Vendedor', max_length=50)),
                ('id_entidad', models.IntegerField(help_text='ID del registro modificado')),
                ('accion', models.CharField(help_text='Ej: Cambio de estado de Pendiente a Pagada', max_length=255)),
                ('nivel_severidad', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error Crítico')], default='INFO', max_length=10)),
                ('usuario_responsable', models.CharField(blank=True, help_text='Quién hizo el cambio', max_length=100, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('detalles_json', models.JSONField(blank=True, help_text='Datos técnicos adicionales en formato JSON', null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
            },
        ),
    ]
