# Generated by Django 6.0.3 on 2026-03-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(max_length=50)),
                ('mensaje_error', models.TextField()),
                ('stacktrace', models.TextField(blank=True, null=True)),
                ('usuario_afectado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Log de Error',
            },
        ),
    ]
