# Generated by Django 6.0.3 on 2026-03-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_logerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logerror',
            options={'verbose_name': 'Log de Error', 'verbose_name_plural': 'Logs de Errores'},
        ),
    ]
