# Generated by Django 6.0.3 on 2026-04-02 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('vendors', '0010_rename_resultado_crediticio_solicitud_resultado_cifin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorcomercial',
            old_name='telefono',
            new_name='telefono_corporativo',
        ),
        migrations.RemoveField(
            model_name='directorcomercial',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='directorcomercial',
            name='user',
        ),
        migrations.AddField(
            model_name='directorcomercial',
            name='cargo',
            field=models.CharField(default='Director Comercial', max_length=100),
        ),
        migrations.AddField(
            model_name='directorcomercial',
            name='dependencia',
            field=models.CharField(default='Gerencia de Ventas', max_length=100),
        ),
        migrations.AddField(
            model_name='directorcomercial',
            name='persona',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to='vendors.persona'),
            preserve_default=False,
        ),
    ]
