# Generated by Django 6.0.3 on 2026-03-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta'), ('ACTIVA', 'Activa'), ('EN_MORA', 'En Mora'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('resultado_crediticio', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('ADVERTENCIA', 'Advertencia'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('resultado_judicial', models.CharField(choices=[('REQUERIDO', 'Requerido'), ('NO_REQUERIDO', 'No Requerido'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='vendors.persona')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
