# Generated by Django 6.0.3 on 2026-03-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUT', 'RUT'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('ACEPTACION_RIESGO', 'Aceptación Centrales de Riesgo'), ('ACEPTACION_DATOS', 'Aceptación Tratamiento de Datos')], max_length=20)),
                ('url_archivo', models.FileField(upload_to='documentos_vendedores/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vendors.solicitud')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_suscripcion', models.CharField(choices=[('INACTIVA', 'Inactiva'), ('ACTIVA', 'Activa'), ('EN_MORA', 'En Mora'), ('CANCELADA', 'Cancelada')], default='INACTIVA', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_profile', to='vendors.persona')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
    ]
