# Generated by Django 6.0.3 on 2026-03-16 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_documento_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Juridica')], max_length=10, null=True),
        ),
    ]
