# Generated by Django 6.0.3 on 2026-03-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_persona_user_alter_persona_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIFIN_Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('dictamen', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cifin_data', to='vendors.persona')),
            ],
            options={
                'verbose_name': 'Consulta CIFIN Local',
            },
        ),
    ]
