# Generated by Django 6.0.3 on 2026-03-16 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_cifin_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCrediticia_Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_cifin', models.IntegerField(blank=True, null=True)),
                ('dictamen_cifin', models.CharField(blank=True, max_length=20, null=True)),
                ('score_datacredito', models.IntegerField(blank=True, null=True)),
                ('dictamen_datacredito', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_data', to='vendors.persona')),
            ],
            options={
                'verbose_name': 'Consulta Crediticia Local',
                'verbose_name_plural': 'Consultas Crediticias Locales',
            },
        ),
        migrations.DeleteModel(
            name='CIFIN_Local',
        ),
    ]
