# Generated by Django 6.0.3 on 2026-03-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_consultacrediticia_local_delete_cifin_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultacrediticia_local',
            name='persona',
        ),
        migrations.AddField(
            model_name='consultacrediticia_local',
            name='solicitud',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_data', to='vendors.solicitud'),
        ),
        migrations.CreateModel(
            name='CalificacionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(choices=[(1, '1 Estrellas'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_realizadas', to='vendors.persona')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='vendors.vendedor')),
            ],
            options={
                'verbose_name': 'Calificación de Vendedor',
                'verbose_name_plural': 'Calificaciones de Vendedores',
            },
        ),
    ]
