# Generated by Django 6.0.3 on 2026-03-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_consultacrediticia_local_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionvendedor',
            name='estrellas',
            field=models.IntegerField(choices=[(1, '1 Estrellas'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas'), (6, '6 Estrellas'), (7, '7 Estrellas'), (8, '8 Estrellas'), (9, '9 Estrellas'), (10, '10 Estrellas')]),
        ),
    ]
