# Generated by Django 6.0.3 on 2026-04-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_persona_direccion_persona_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='resultado_crediticio',
            new_name='resultado_cifin',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='resultado_datacredito',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('ADVERTENCIA', 'Advertencia'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
