# Generated by Django 6.0.3 on 2026-04-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_rename_resultado_crediticio_solicitud_resultado_cifin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_consulta_judicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
