# Generated by Django 6.0.3 on 2026-03-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_imagenproducto'),
        ('vendors', '0003_documento_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CARRITO', 'Carrito Activo'), ('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada / Completada'), ('ENVIADA', 'Enviada'), ('CANCELADA', 'Cancelada')], default='carrito', max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('RECOGER', 'Recoger en punto'), ('DOMICILIO', 'Entrega en domicilio')], default='RECOGER', max_length=20)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='vendors.persona')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_orden', to='products.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealles', to='orders.orden')),
            ],
        ),
    ]
