# Generated by Django 6.0.3 on 2026-03-12 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name': 'Detalle de orden', 'verbose_name_plural': 'Detalles de orden'},
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.orden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('CARRITO', 'Carrito Activo'), ('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada / Completada'), ('ENVIADA', 'Enviada'), ('CANCELADA', 'Cancelada')], default='CARRITO', max_length=20),
        ),
    ]
