# Generated by Django 6.0.3 on 2026-03-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_detalleorden_options_alter_detalleorden_orden_and_more'),
        ('products', '0008_producto_descripcion'),
        ('vendors', '0008_alter_calificacionvendedor_estrellas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_producto', to='vendors.persona')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='orders.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='products.producto')),
            ],
            options={
                'verbose_name': 'Calificación de Producto',
                'verbose_name_plural': 'Calificaciones de Productos',
                'unique_together': {('producto', 'orden', 'comprador')},
            },
        ),
    ]
