# Generated by Django 6.0.3 on 2026-05-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_calificacionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
