# Generated by Django 6.0.3 on 2026-03-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('vendors', '0007_remove_consultacrediticia_local_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_hash', models.CharField(blank=True, help_text='Hash de validez legal', max_length=255, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_recibidos', to='vendors.persona')),
            ],
            options={
                'verbose_name': 'Correo Enviado',
                'verbose_name_plural': 'Correos Enviados',
            },
        ),
    ]
