# Generated by Django 6.0.3 on 2026-04-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_correoenviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('SOLICITUD', 'Actualización de Solicitud'), ('COMPRA', 'Nueva Compra'), ('SISTEMA', 'Aviso del Sistema'), ('PREGUNTA', 'Nueva Pregunta'), ('RESPUESTA', 'Respuesta Recibida')], max_length=20),
        ),
    ]
