# Generated by Django 6.0.3 on 2026-03-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0003_documento_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, help_text='5.00 para 5%', max_digits=5)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('originalidad', models.CharField(choices=[('ORIGINAL', 'Original'), ('GENERICO', 'Generico')], default='ORIGINAL', max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('tamano', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=10)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('condicion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], default='NUEVO', max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='vendors.vendedor')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.subcategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
