# Generated by Django 6.0.3 on 2026-03-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comentarioproducto_preguntaproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='originalidad',
            new_name='autenticidad',
        ),
    ]
