# Generated by Django 6.0.3 on 2026-03-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_originalidad_producto_autenticidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('peso_min', models.DecimalField(decimal_places=2, help_text='En kg', max_digits=10)),
                ('peso_max', models.DecimalField(decimal_places=2, help_text='En kg', max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Costo de Domicilio',
                'verbose_name_plural': 'Costos de Domicilio',
            },
        ),
    ]
