# Generated by Django 6.0.3 on 2026-03-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comentarioproducto_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioproducto',
            name='calificacion',
        ),
    ]
