# Generated by Django 6.0.3 on 2026-03-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_comentarioproducto_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='', help_text='Descripción detallada del producto'),
            preserve_default=False,
        ),
    ]
