# Generated by Django 6.0.3 on 2026-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioproducto',
            name='calificacion',
            field=models.IntegerField(default=10, help_text='Calificación de 1 a 10'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ventas_totales',
            field=models.IntegerField(default=0, help_text='Contador para productos destacados'),
        ),
    ]
