# Generated by Django 6.0.3 on 2026-04-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_calificacionproducto'),
        ('products', '0010_comentarioproducto_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioproducto',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_productos', to='orders.orden'),
        ),
    ]
