# Generated by Django 6.0.3 on 2026-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comentarioproducto_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioproducto',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='respuesta_vendedor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
