# Generated by Django 6.0.3 on 2026-04-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_calificacionproducto'),
        ('products', '0011_comentarioproducto_orden'),
        ('vendors', '0011_solicitud_fecha_consulta_judicial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentarioproducto',
            unique_together={('producto', 'orden', 'comprador')},
        ),
    ]
