# Generated by Django 6.0.3 on 2026-04-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comentarioproducto_fecha_respuesta_and_more'),
        ('products', '0012_alter_comentarioproducto_unique_together'),
    ]

    operations = [
    ]
