# Generated by Django 6.0.3 on 2026-04-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20260412_2047'),
        ('products', '0013_merge_20260413_1841'),
    ]

    operations = [
    ]
