# Generated by Django 6.0.3 on 2026-04-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20260418_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['-es_principal', 'id'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
    ]
