# Generated by Django 6.0.3 on 2026-05-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_imagenproducto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='costodomicilio',
            name='costo_kilo_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo adicional por cada kg que exceda el peso_max', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costodomicilio',
            name='ciudad',
            field=models.CharField(help_text='Nombre de la ciudad (ej: BOGOTA)', max_length=100),
        ),
        migrations.AlterField(
            model_name='costodomicilio',
            name='costo',
            field=models.DecimalField(decimal_places=2, help_text='Precio base para este rango', max_digits=12),
        ),
        migrations.AlterField(
            model_name='costodomicilio',
            name='peso_max',
            field=models.DecimalField(decimal_places=2, help_text='Peso máximo en kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costodomicilio',
            name='peso_min',
            field=models.DecimalField(decimal_places=2, help_text='Peso mínimo en kg', max_digits=10),
        ),
    ]
